apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      command:
        - tail
        - -f
        - /dev/null
    - name: curl
      image: "alpine/curl:8.10.0"
      command:
        - tail
        - -f
        - /dev/null